[template]
cargo_generate_version = "0.23"
include = ["*.template"]
ignore = [
    "LICENSE-Apache-2.0.txt",
    "LICENSE-CC0-1.0.txt",
    "LICENSE-MIT.txt",
]

[hooks]
post = ["post-generate.rhai"]
